###
# Crear un nuevo usuario
###

POST http://localhost:3001/api/v1/usuarios/createUsuario
Content-Type: application/json

{
    "Correo": "nuevo_usuario@example.com",
    "Nombre": "Nuevo",
    "Apellido": "Usuario",
    "Telefono": "1234567890",
    "Contrasena": "nuevacontrasena",
    "Role": "USUARIO"
}

###
#Crear nuevo producto
###

POST http://localhost:3001/api/v1/productos/createProducto
Content-Type: application/json

{
        "Nombre": "abc",
        "Descripcion": "abc",
        "Precio": 1.200,
        "Stock": 5,
        "Imagen": "abc",
        "Color": "abc",
        "Medidas" : "abc"
}

###
GET http://localhost:3001/api/v1/productos/getAllProductos
Content-Type: application/json

